include_guard(GLOBAL)

set(PROTOCYTE_REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
set(PROTOCYTE_PYTHON_SOURCE_ROOT "${PROTOCYTE_REPO_ROOT}/src")
set(PROTOCYTE_PACKAGE_ROOT "${PROTOCYTE_PYTHON_SOURCE_ROOT}/protocyte")
set(PROTOCYTE_PROTO_DIR "${PROTOCYTE_PACKAGE_ROOT}/proto")
set(PROTOCYTE_OPTIONS_PROTO "${PROTOCYTE_PROTO_DIR}/protocyte/options.proto")
set(
    PROTOCYTE_GENERATOR_SOURCES
    "${PROTOCYTE_PACKAGE_ROOT}/__init__.py"
    "${PROTOCYTE_PACKAGE_ROOT}/cpp.py"
    "${PROTOCYTE_PACKAGE_ROOT}/errors.py"
    "${PROTOCYTE_PACKAGE_ROOT}/main.py"
    "${PROTOCYTE_PACKAGE_ROOT}/model.py"
    "${PROTOCYTE_PACKAGE_ROOT}/parameters.py"
    "${PROTOCYTE_PACKAGE_ROOT}/plugin.py"
    "${PROTOCYTE_PACKAGE_ROOT}/runtime.py"
)

set_property(GLOBAL PROPERTY PROTOCYTE_INTERNAL_PYTHON_SOURCE_ROOT "${PROTOCYTE_PYTHON_SOURCE_ROOT}")
set_property(GLOBAL PROPERTY PROTOCYTE_INTERNAL_PROTO_DIR "${PROTOCYTE_PROTO_DIR}")
set_property(GLOBAL PROPERTY PROTOCYTE_INTERNAL_OPTIONS_PROTO "${PROTOCYTE_OPTIONS_PROTO}")
set_property(GLOBAL PROPERTY PROTOCYTE_INTERNAL_GENERATOR_SOURCES "${PROTOCYTE_GENERATOR_SOURCES}")

include("${CMAKE_CURRENT_LIST_DIR}/ProtocyteFunctions.cmake")
